# {\r\n    \"@context\": \"https:\/\/schema.org\",\r\n    \"@type\": \"Person\"\r\n  }
POST http://localhost:3000/posts
Content-Type: application/json

{
  "title": "What's new with NestJS",
  "postType": "post",
  "slug": "new-with-nest-js",
  "status": "draft",
  "content": "post-content",
  "featuredImageUrl": "http://localhost.com/images/image1.jpg",
  "publishOn": "2024-03-16T07:46:32+0000",
  "author": "6723ddd43d3a5f70ddabd04a",
  "tags": ["6723f58baaf93f5ace99e7f9", "6723f64fb20270248e092025"]
}
